
from app.graph.state import BusinessState
from app.services.business_analysis_service import analyze_business_question


def analysis_node(state: BusinessState) -> dict:
    question = state["question"]
    plan = state["plan"]

    result = analyze_business_question(
        f"""
        Original business question:
        {question}

        Analysis plan generated by the Planner:
        {plan}

        Follow this plan where it is relevant.
        Use only the available data.
        Clearly distinguish observed facts from hypotheses.
        """
    )

    return {
        "analysis": result["analysis"],
        "metrics": result["metrics"].model_dump(),
    }
